version: '2'

services:
  myweb:
    image: ifew/nginx_php:7.3
    container_name: myweb
    env_file: .env
    environment:
      - MYSQL_DB_HOST="${MYSQL_DB_HOST}"
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - TEST="${TEST}"
    networks:
      - app-web
    links:
      - mysql
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/app/
  mysql:
    image: mysql:5.7.35
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_ROOT_USER="${MYSQL_ROOT_USER}"
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    networks:
      - app-web

networks:
  app-web:
    driver: bridge